export type FormAvailability = "open" | "opening_soon" | "watch" | "closed" | "not_eligible";

export type FormChecklistSeed = {
  title: string;
  type: "application_form" | "leadership_form";
  url: string;
  status: string;
  notes: {
    target: string;
    region: string;
    stage: string;
    priority: "P1" | "P2" | "P3";
    cycle: string;
    deadline: string;
    action: string;
    why: string;
    documents: string[];
    route: string;
    evidence?: string;
    sourceConfidence: string;
    availability?: FormAvailability;
    openDate?: string;
    deadlineDate?: string;
    lastChecked?: string;
  };
};

const checked = "2026-09-07";

export const formChecklistSeeds: FormChecklistSeed[] = [
  {
    title: "Chevening India Scholarship Application",
    type: "application_form",
    url: "https://www.chevening.org/scholarship/india/",
    status: "live_open",
    notes: {
      target: "Chevening Scholarship India 2027-2028",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027/28 applications are open now",
      deadline: "6 Oct 2026, 11:00 UTC",
      action: "Create the Chevening account now. Draft the four essays, shortlist three eligible one-year UK master's courses, and confirm two referees before the last week of September.",
      why: "This is the most urgent live funding form because it can fund a UK master's and Chevening explicitly says India applications are open for 2027-2028.",
      documents: ["Passport", "Email and phone", "Unique access code", "Three UK course choices", "Leadership essay", "Networking essay", "Study in UK essay", "Career plan essay", "Two referees"],
      route: "scholarships",
      evidence: "Use Mentally Prepare, HPAIR, HP Dreams Unlocked, IIT Kharagpur, your UX Researcher internship, and the derealization/gaming paper as leadership plus impact proof.",
      sourceConfidence: `Official Chevening India page and timeline checked ${checked}`,
      availability: "open",
      openDate: "2026-08-04",
      deadlineDate: "2026-10-06",
      lastChecked: checked,
    },
  },
  {
    title: "Commonwealth Master's Scholarship Application",
    type: "application_form",
    url: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
    status: "opening_soon",
    notes: {
      target: "Commonwealth Master's Scholarships 2027/28",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027/28 opens 8 Sep 2026",
      deadline: "20 Oct 2026, 16:00 BST",
      action: "Prepare answers outside CSC Central first, then paste only final text. Identify the India nominating route, collect two PDF references, and make a development-impact argument around student mental health.",
      why: "CSC says applications open on 8 September 2026, close on 20 October 2026, and late or external documents are not accepted.",
      documents: ["Passport", "Full transcript", "Certified translations if needed", "Two PDF references", "Development impact statement", "Course choices", "Nominator route notes", "2FA backup email or phone"],
      route: "scholarships",
      evidence: "Your strongest angle is mental-health access for students in India, backed by Mentally Prepare, psychology training, UX research, and research work.",
      sourceConfidence: `Official Commonwealth Scholarship Commission page checked ${checked}`,
      availability: "opening_soon",
      openDate: "2026-09-08",
      deadlineDate: "2026-10-20",
      lastChecked: checked,
    },
  },
  {
    title: "Knight-Hennessy Scholars Application",
    type: "application_form",
    url: "https://knight-hennessy.stanford.edu/admission/preparing-your-applications/application-deadlines",
    status: "live_open",
    notes: {
      target: "Stanford Knight-Hennessy Scholars 2027 cohort",
      region: "USA",
      stage: "Scholarship form",
      priority: "P2",
      cycle: "2027 cohort application is open",
      deadline: "6 Oct 2026, 1:00 PM Pacific Time",
      action: "Only pursue if you add a Stanford graduate program to the shortlist. KHS requires a separate KHS application plus a separate Stanford graduate application by the earlier program deadline or 1 Dec 2026.",
      why: "It is live and fully funded, but it is Stanford-specific and extremely competitive, so it should not distract from Chevening/Commonwealth unless Stanford becomes a real target.",
      documents: ["KHS application", "Separate Stanford graduate application", "Resume", "Transcripts", "Recommendation letters", "Short answers", "Essay", "Video statement prep"],
      route: "scholarships",
      evidence: "Position as psychology researcher building mental-health technology and studying digital behaviour.",
      sourceConfidence: `Official Knight-Hennessy deadline page checked ${checked}`,
      availability: "open",
      openDate: "2026-06-01",
      deadlineDate: "2026-10-06",
      lastChecked: checked,
    },
  },
  {
    title: "CMU MHCI Application",
    type: "application_form",
    url: "https://admissions.scs.cmu.edu/portal/apply_mhci",
    status: "opening_soon",
    notes: {
      target: "Carnegie Mellon Master of Human-Computer Interaction, Fall 2027",
      region: "USA",
      stage: "Admission portal",
      priority: "P1",
      cycle: "Fall 2027 application opens 9 Sep 2026",
      deadline: "15 Jan 2027, 3:00 PM EST",
      action: "Prepare statement, resume, transcript, recommenders, IELTS/TOEFL plan, and two portfolio examples before the portal opens. Make one UX Researcher internship case study and one Mentally Prepare HCI case study.",
      why: "CMU's SCS portal states MHCI Fall 2027 opens on 9 September 2026 with one final deadline on 15 January 2027.",
      documents: ["Statement", "Resume", "Transcript", "Letters of recommendation", "IELTS/TOEFL score plan", "Portfolio/examples of work", "Application fee"],
      route: "applications",
      evidence: "Use the UX Researcher internship as your core professional proof; use Mentally Prepare as human-centred product proof.",
      sourceConfidence: `Official CMU SCS/MHCI application portal checked ${checked}`,
      availability: "opening_soon",
      openDate: "2026-09-09",
      deadlineDate: "2027-01-15",
      lastChecked: checked,
    },
  },
  {
    title: "UPenn MBDS Fall 2027 Application",
    type: "application_form",
    url: "https://www.lps.upenn.edu/degree-programs/mbds/application",
    status: "opening_soon",
    notes: {
      target: "University of Pennsylvania Master of Behavioral and Decision Sciences",
      region: "USA",
      stage: "Admission portal",
      priority: "P1",
      cycle: "Fall 2027 applications open in mid-September 2026",
      deadline: "Priority 1 Dec 2026; regular 1 Feb 2027",
      action: "Start WES planning now because Penn says international credential evaluation can take 8-12 weeks. Prepare GRE unless you have three years of full-time post-bachelor work experience.",
      why: "Penn MBDS is one of the cleanest USA behavioural science fits and the official page says early submission improves enrollment consideration.",
      documents: ["Short-answer question", "Resume", "Unofficial transcripts", "WES course-by-course evaluation", "GRE if required", "IELTS/TOEFL", "Two recommendations", "Application fee"],
      route: "applications",
      evidence: "Connect consumer psychology, UX research, Mentally Prepare, and behavioural decision science into a product-research career path.",
      sourceConfidence: `Official Penn MBDS application page checked ${checked}`,
      availability: "opening_soon",
      openDate: "2026-09-15",
      deadlineDate: "2026-12-01",
      lastChecked: checked,
    },
  },
  {
    title: "GRE General Test Registration",
    type: "application_form",
    url: "https://www.ets.org/gre/test-takers/general-test/register.html",
    status: "test_core",
    notes: {
      target: "GRE General Test for USA behavioural science / HCI options",
      region: "USA",
      stage: "Test booking",
      priority: "P1",
      cycle: "October 2026 test plan",
      deadline: "Book September; take GRE in October 2026 with retake buffer",
      action: "Create the ETS account, choose GRE General Test, select an October test date, and map score-send codes for Penn MBDS plus any other USA program that requires or recommends GRE.",
      why: "Penn MBDS requires GRE for applicants with less than three years of full-time post-bachelor employment, excluding internships. Aashi should treat GRE as USA-specific, not as a universal requirement.",
      documents: ["Passport name match", "ETS account", "Test centre or at-home choice", "Payment", "Target Quant 160+", "Target Verbal 160+", "AWA 4.0+", "Score recipient list", "Retake buffer"],
      route: "ielts",
      evidence: "Use GRE as academic/quant proof for Penn MBDS and other USA analytical routes; do not spend GRE energy on UK courses that do not ask for it.",
      sourceConfidence: `Official ETS GRE registration page and Penn MBDS requirement checked ${checked}`,
      availability: "open",
      deadlineDate: "2026-09-30",
      lastChecked: checked,
    },
  },
  {
    title: "NYU MA Psychology Application",
    type: "application_form",
    url: "https://as.nyu.edu/departments/psychology/graduate/ma-application-info.html",
    status: "admission_watch",
    notes: {
      target: "NYU MA Psychology, Social and Consumer Psychology pathway",
      region: "USA",
      stage: "Admission portal",
      priority: "P2",
      cycle: "Fall deadline watch",
      deadline: "Official NYU psychology page lists 15 Feb for Fall admission",
      action: "Verify the live Fall 2027 portal when NYU refreshes. Prepare Intro Psychology, Statistics, SOP, resume, transcript and letters before February.",
      why: "NYU is the direct Consumer Psychology reference route, but the official page is protected behind JS checks, so keep it as a verified-watch item until the portal is visible.",
      documents: ["Transcript", "SOP", "Resume", "Recommendation letters", "Statistics proof", "Intro psychology proof", "IELTS/TOEFL if required"],
      route: "applications",
      evidence: "Use consumer behaviour, social media analytics, UX research, and Mentally Prepare research insights.",
      sourceConfidence: `Official NYU application page located; deadline checked from official search result ${checked}`,
      availability: "watch",
      deadlineDate: "2027-02-15",
      lastChecked: checked,
    },
  },
  {
    title: "LSE Graduate Application",
    type: "application_form",
    url: "https://www.lse.ac.uk/study-at-lse/graduate/prospective-students/how-to-apply",
    status: "admission_watch",
    notes: {
      target: "LSE MSc Behavioural Science",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027/28 applications open in October 2026",
      deadline: "Apply in October/November once the 2027/28 portal opens",
      action: "Build the full LSE packet before October: statement of academic purpose, CV, two referees, transcript, IELTS plan, research summary and programme fit notes.",
      why: "LSE says competition is intense, early applications have better chances for admission/funding/visa deadlines, and applications are processed only after references arrive.",
      documents: ["Transcript", "CV", "Statement of academic purpose", "Two references", "English test plan", "Research summary", "Behavioural Lab/faculty fit notes"],
      route: "applications",
      evidence: "Use the derealization/gaming paper and Mentally Prepare as the behavioural science proof spine.",
      sourceConfidence: `Official LSE graduate application timing checked ${checked}`,
      availability: "opening_soon",
      openDate: "2026-10-01",
      lastChecked: checked,
    },
  },
  {
    title: "LSE Graduate Financial Support Application",
    type: "application_form",
    url: "https://www.lse.ac.uk/study-at-lse/graduate/fees-and-funding/pgt-application-overview",
    status: "scholarship_watch",
    notes: {
      target: "LSE Graduate Support Scheme and LSE scholarships",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027/28 funding date not yet published",
      deadline: "Watch after LSE application opens; 2026/27 funding deadline was 23 Apr 2026",
      action: "Submit the LSE admission application early, then complete the Graduate Financial Support Application as soon as the Graduate Applicant Portal exposes it.",
      why: "LSE funding depends on the admission application and offer timeline, so late references can block scholarship consideration.",
      documents: ["LSE application number", "Funding statement", "Budget", "Family/financial evidence", "Offer condition watch", "Safe senders for lse.ac.uk"],
      route: "scholarships",
      evidence: "Tie financial need to a focused plan: behavioural science, mental health technology, and return-on-investment.",
      sourceConfidence: `Official LSE fees and funding pages checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "UCL Graduate Taught Application",
    type: "application_form",
    url: "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/behaviour-change-msc",
    status: "admission_watch",
    notes: {
      target: "UCL Behaviour Change MSc",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2026/27 closed; 2027/28 page watch",
      deadline: "Visa-applicant deadline for 2026/27 was 27 Mar 2026; non-visa deadline was 28 Aug 2026",
      action: "Use September to prepare; do not wait for the portal. UCL asks why Behaviour Change, why UCL, how your background meets the course, and where you want to go professionally.",
      why: "UCL has the strongest behaviour-change intervention fit; the course requires research experience and benefits from practical behaviour-change work.",
      documents: ["Transcript", "Personal statement", "CV", "Two references", "English Level 2 check", "Research experience paragraph", "Behaviour-change portfolio note"],
      route: "applications",
      evidence: "Use UX Researcher internship as practical behaviour-change/research experience.",
      sourceConfidence: `Official UCL Behaviour Change MSc page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "UCL Global Master's Scholarship",
    type: "application_form",
    url: "https://www.ucl.ac.uk/scholarships/ucl-global-masters-scholarship",
    status: "scholarship_closed_watch",
    notes: {
      target: "UCL Global Master's Scholarship",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2026/27 closed; 2027/28 watch",
      deadline: "2026/27 deadline was 7 May 2026, 5:00 PM BST",
      action: "Prepare financial-need evidence now, but do not mark this as open. The required first step is a complete UCL admission application with references.",
      why: "UCL states the Global Master's award is GBP 15,000 and had India ring-fenced places in 2026/27, but the live 2027/28 date is not published yet.",
      documents: ["UCL application number", "References submitted", "Fee status", "Financial need evidence", "Scholarship statement", "Budget"],
      route: "scholarships",
      evidence: "Frame need plus high-impact plan: behavioural science for student wellbeing and digital behaviour.",
      sourceConfidence: `Official UCL Global Master's Scholarship page checked ${checked}`,
      availability: "closed",
      deadlineDate: "2026-05-07",
      lastChecked: checked,
    },
  },
  {
    title: "UCL India Excellence Scholarship",
    type: "application_form",
    url: "https://www.ucl.ac.uk/scholarships/ucl-india-excellence-scholarship",
    status: "scholarship_closed_watch",
    notes: {
      target: "UCL India Excellence Scholarship",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2026/27 closed; 2027/28 watch",
      deadline: "2026/27 deadline was 26 Feb 2026, 5:00 PM BST",
      action: "No separate scholarship form was required in 2026/27. Your action is to submit a complete UCL admission application with references before the scholarship pool deadline once 2027/28 refreshes.",
      why: "UCL shortlisted automatically by admission application, GPA, NIRF institution background and offer status.",
      documents: ["Complete UCL admission application", "References submitted", "NIRF institution proof", "GPA/class proof", "Offer status"],
      route: "scholarships",
      evidence: "This depends heavily on GPA/class strength. Keep Christ transcript and grading explanation clean.",
      sourceConfidence: `Official UCL India Excellence Scholarship page checked ${checked}`,
      availability: "closed",
      deadlineDate: "2026-02-26",
      lastChecked: checked,
    },
  },
  {
    title: "Warwick Behavioural and Economic Science Application",
    type: "application_form",
    url: "https://warwick.ac.uk/study/postgraduate/courses/msc-behavioural-economics-science/",
    status: "admission_watch",
    notes: {
      target: "Warwick MSc Behavioural and Economic Science",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2026 entry closed; 2027/28 watch",
      deadline: "Prepare for early round when next cycle opens",
      action: "Prepare quant/statistics evidence now because the course is methods-heavy. Watch October for the next applicant portal cycle.",
      why: "Warwick listed early, middle and final rounds for 2026, and the final deadline was extended to 2 August 2026.",
      documents: ["Transcript", "CV", "Personal statement", "Reference", "Statistics/methods evidence", "IELTS Band B plan"],
      route: "applications",
      evidence: "Make a quantitative appendix for your research paper and UX internship methods.",
      sourceConfidence: `Official Warwick course page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "Warwick Behavioural and Data Science Application",
    type: "application_form",
    url: "https://warwick.ac.uk/fac/sci/psych/bds/",
    status: "admission_watch",
    notes: {
      target: "Warwick MSc Behavioural and Data Science",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027/28 application information is TBC",
      deadline: "Watch Warwick Psychology page; 2026/27 applications are closed",
      action: "Treat this as Warwick's stronger UX/data-research alternative. Build R/statistics, research design, and behavioural data evidence before the 2027/28 rules are posted.",
      why: "Warwick's Psychology page has a live 2027/28 heading but the detailed consideration rounds are still TBC.",
      documents: ["Transcript", "CV", "Personal statement", "Reference", "Statistics/R evidence", "UX research case study", "Research methods summary"],
      route: "applications",
      evidence: "This is where your UX Researcher internship can become a direct admissions advantage.",
      sourceConfidence: `Official Warwick Psychology BDS page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "Erasmus Studielink + EUR Admissions Portal",
    type: "application_form",
    url: "https://www.eur.nl/en/ese/education/master/application/students-international-diploma/application-procedure-economics-and-business",
    status: "admission_watch",
    notes: {
      target: "Erasmus MSc Economics and Business, Behavioural Economics specialisation",
      region: "Netherlands",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2026/27 closed; next application period expected in fall",
      deadline: "Previous non-EU/EEA deadline was 1 Apr 2026",
      action: "Prepare for Studielink first, then EUR Admissions Portal. Studielink alone is not the real application; the specialisation is selected in the EUR portal.",
      why: "EUR says 2026/27 applications are closed and applicants should check the website again in the fall for next year's application period.",
      documents: ["Diploma or graduation statement", "Official transcript", "Certified translations if needed", "EUR portal questions", "Application fee if applicable", "Behavioural Economics specialisation choice"],
      route: "applications",
      evidence: "Show economics/statistics readiness plus consumer behaviour and UX research fit.",
      sourceConfidence: `Official Erasmus School of Economics application procedure checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "Erasmus Trustfonds Scholarship",
    type: "application_form",
    url: "https://www.eur.nl/en/ese/education/master/fees-and-scholarships/scholarships-and-grants/erasmus-trustfonds-scholarship",
    status: "scholarship_watch",
    notes: {
      target: "Erasmus Trustfonds Scholarship",
      region: "Netherlands",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027/28 watch; 2026/27 window was 1 Dec 2025 to 31 Jan 2026",
      deadline: "Expected watch window: Dec-Jan; verify when EUR refreshes",
      action: "Prepare the financial statement, budget plan, certified transcript and GPA statement before the admission portal opens.",
      why: "For 2026/27, Erasmus Trustfonds required Studielink registration and submitted EUR portal documents before the scholarship deadline.",
      documents: ["Studielink registration", "EUR application", "Financial statement", "Budget plan", "Certified transcript", "GPA statement", "Scholarship application"],
      route: "scholarships",
      evidence: "Use academic excellence plus financial need and a high-ROI behavioural economics plan.",
      sourceConfidence: `Official Erasmus scholarship page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "Philip Hans Franses Scholarship",
    type: "application_form",
    url: "https://www.eur.nl/en/ese/education/master/fees-and-scholarships/scholarships-and-grants/philip-hans-franses-scholarship",
    status: "scholarship_watch",
    notes: {
      target: "Erasmus School of Economics non-EEA scholarship",
      region: "Netherlands",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027/28 watch; 2026/27 window was 1 Dec 2025 to 1 Feb 2026",
      deadline: "Build before expected 1 Feb cycle deadline",
      action: "Prepare motivation letter, financial statement, budget plan, certified transcript and GPA statement, then submit through Osiris Student when open.",
      why: "EUR previously listed awards and tuition-fee waiver support for eligible non-EEA master students.",
      documents: ["Motivation letter", "Financial statement", "Budget plan", "Certified transcript", "GPA statement", "Osiris Student application"],
      route: "scholarships",
      evidence: "Make the motivation letter specific: Behavioural Economics plus mental-health/product impact in India.",
      sourceConfidence: `Official Erasmus scholarship page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "DAAD Master's Scholarship Application",
    type: "application_form",
    url: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50026200",
    status: "scholarship_watch",
    notes: {
      target: "DAAD Study Scholarships - Master Studies for All Academic Disciplines",
      region: "Germany",
      stage: "Scholarship form",
      priority: "P2",
      cycle: "Applications possible between 1 June and the stated country/program deadline",
      deadline: "Use DAAD database for exact India deadline before submission",
      action: "Make a Germany shortlist first. Then prepare CV, motivation letter, admission/host programme info, transcript, language proof and one university teacher recommendation.",
      why: "DAAD says deadlines are updated annually and the portal is visible only during the current application period.",
      documents: ["CV max 3 pages", "Motivation letter 1-3 pages", "Programme/admission letter or course profile", "Transcript", "Degree certificate if available", "Language proof", "University teacher recommendation", "Optional certificates"],
      route: "scholarships",
      evidence: "Best fit only if Germany has a behavioural science, HCI, digital society or psychology programme that clearly fits your path.",
      sourceConfidence: `Official DAAD scholarship database checked ${checked}`,
      availability: "watch",
      openDate: "2026-06-01",
      lastChecked: checked,
    },
  },
  {
    title: "Inlaks Shivdasani Scholarship Watch",
    type: "application_form",
    url: "https://inlaksfoundation.org/opportunities/scholarship/",
    status: "scholarship_closed_watch",
    notes: {
      target: "Inlaks Scholarship for overseas study",
      region: "Global",
      stage: "Scholarship form",
      priority: "P2",
      cycle: "Applications closed for 2026; next cycle not announced",
      deadline: "Watch for next application opening",
      action: "Do not waste time looking for an Apply button today. Build the offer, GPA, and funding documents so you can move fast when the next cycle opens.",
      why: "Inlaks currently says applications closed for 2026 and the Apply Now link appears only when applications are open.",
      documents: ["Offer letter", "GPA proof", "Passport", "SOP/project rationale", "Financial proof if cost exceeds award", "Portfolio if relevant"],
      route: "scholarships",
      evidence: "A behavioural science or consumer psychology offer can fit better than management/MBA routes, which Inlaks excludes.",
      sourceConfidence: `Official Inlaks Scholarship page checked ${checked}`,
      availability: "closed",
      lastChecked: checked,
    },
  },
  {
    title: "Inlaks-King's India Institute Studentship",
    type: "application_form",
    url: "https://inlaksfoundation.org/opportunities/grants/inlaks-kings-india-institute-studentship/",
    status: "not_eligible_now",
    notes: {
      target: "Inlaks-King's India Institute Studentship",
      region: "UK",
      stage: "Research grant",
      priority: "P3",
      cycle: "2026 applications closed; PhD-only route",
      deadline: "Not eligible now",
      action: "Keep as future PhD/research-route intelligence only. Do not prioritize for current master's applications.",
      why: "The official page says this supports scholars currently enrolled in PhD programmes at Indian universities and requires PhD synopsis confirmation.",
      documents: ["PhD synopsis confirmation", "First-class Bachelor and Master degree", "Humanities/social sciences research plan", "Potential supervisors list"],
      route: "research",
      evidence: "Useful later if your path becomes PhD/research, not for final-year BSc master's admission today.",
      sourceConfidence: `Official Inlaks-King's page checked ${checked}`,
      availability: "not_eligible",
      lastChecked: checked,
    },
  },
  {
    title: "IELTS Academic Registration",
    type: "application_form",
    url: "https://www.idp.com/india/ielts/book-a-test/",
    status: "test_core",
    notes: {
      target: "IELTS Academic for UK, Europe and USA applications",
      region: "Global",
      stage: "Test booking",
      priority: "P1",
      cycle: "Book once target score is realistic; India IELTS testing is through IDP",
      deadline: "Book early enough for score reporting and retake buffer",
      action: "Book IELTS Academic, not General Training. Keep a retake buffer because CMU/Penn/UK scholarship deadlines can punish late scores.",
      why: "English score is a gatekeeping form: it unlocks admission, visa and scholarships.",
      documents: ["Passport", "Test city/date", "Payment", "Target band plan", "Score recipient list", "Retake buffer"],
      route: "ielts",
      evidence: "Use IELTS as a readiness lever, not a last-minute paperwork item.",
      sourceConfidence: `IELTS/IDP India booking source checked ${checked}`,
      availability: "open",
      lastChecked: checked,
    },
  },
  {
    title: "UCAS Applying Hub",
    type: "application_form",
    url: "https://www.ucas.com/applying",
    status: "planning_reference",
    notes: {
      target: "UK application literacy reference",
      region: "UK",
      stage: "Planning reference",
      priority: "P3",
      cycle: "Reference only for your current master's targets unless a course page instructs UCAS",
      deadline: "Use before building your UK checklist",
      action: "Use UCAS to understand UK deadlines, personal statements, English tests and finance language. For LSE/UCL/Warwick graduate applications, follow the university's own portal.",
      why: "UCAS is useful for structure, but your current behavioural-science master's targets are direct university applications.",
      documents: ["UK timeline notes", "Personal statement guidance", "English test guidance", "Funding notes"],
      route: "sources",
      sourceConfidence: `Official UCAS applying hub checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "BCG ASPIRE Women's Workshop",
    type: "leadership_form",
    url: "https://careers.bcg.com/global/en/featured-events/aspire-womens-workshop",
    status: "leadership_watch",
    notes: {
      target: "BCG ASPIRE Women's Workshop",
      region: "Global",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "2027 watch; 2026 workshop was 2026-05-20 to 2026-05-22",
      deadline: "Check country-specific links when applications reopen",
      action: "Apply through one participating office only. Prepare resume and country-specific documents, then complete the games assessment if invited.",
      why: "ASPIRE is a strong leadership and consulting signal; BCG states there is no participation fee and travel/accommodation are covered for the workshop.",
      documents: ["Leadership CV", "Transcript", "Office choice", "Geographic ties", "Games assessment readiness"],
      route: "opportunities",
      evidence: "Use Mentally Prepare, HPAIR, HP Dreams Unlocked, IIT Kharagpur and UX internship as leadership evidence.",
      sourceConfidence: `Official BCG ASPIRE page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "McKinsey Next Generation Women Leaders",
    type: "leadership_form",
    url: "https://www.mckinsey.com/next-generation-women-leaders",
    status: "leadership_watch",
    notes: {
      target: "McKinsey NGWL",
      region: "Global",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "2027 watch; Europe 2026 deadline was 2026-02-23",
      deadline: "Check Asia-Pacific and Europe pages when next cohort opens",
      action: "Prepare English resume, transcripts and office/function preference. Only apply where you have the required geographic or language fit.",
      why: "McKinsey NGWL asks for grades, work experience, extracurriculars, achievements, transcripts and office/function choices.",
      documents: ["Resume in English", "High school transcript", "University transcript", "Office/function choices", "Leadership examples"],
      route: "opportunities",
      evidence: "Frame yourself as psychology researcher plus mental-health product builder, not just a psychology student.",
      sourceConfidence: `Official McKinsey NGWL page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "EY NextGen Women India",
    type: "leadership_form",
    url: "https://www.ey.com/en_in/careers/nextgen-women",
    status: "leadership_watch",
    notes: {
      target: "EY NextGen Women in Strategy and Transactions",
      region: "India",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "Next India cycle watch; 2026 winner announced",
      deadline: "Use country-level EY page/contact when applications reopen",
      action: "Prepare a strategy/transactions aligned application around curiosity, problem solving, leadership and business impact.",
      why: "EY says the competition is for women currently studying at university level who are interested in Strategy and Transactions.",
      documents: ["Leadership CV", "Academic record", "Strategy interest paragraph", "Achievement examples", "Mentally Prepare impact"],
      route: "opportunities",
      evidence: "Connect consumer psychology, UX research and venture-building to strategy and transactions problem solving.",
      sourceConfidence: `Official EY India page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
  {
    title: "Bain True North Scholarship for Women India",
    type: "leadership_form",
    url: "https://www.bain.com/careers/work-with-us/internships-programs/true-north-scholarship-for-women-india/",
    status: "leadership_watch",
    notes: {
      target: "Bain True North Scholarship for Women India",
      region: "India",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "Apply in Spring 2027; 2026 applications closed",
      deadline: "Spring 2027 watch",
      action: "Prepare consulting CV, academic proof and leadership stories. Confirm eligibility because Bain India says the programme is for women in penultimate undergraduate year.",
      why: "The India programme offers a workshop, INR 75,000 scholarship opportunity and possible full-time interview route.",
      documents: ["Consulting CV", "Transcript", "Leadership story", "Problem-solving examples", "Penultimate-year eligibility check"],
      route: "opportunities",
      evidence: "Use HP Dreams Unlocked, HPAIR, IIT Kharagpur, Mentally Prepare and UX research as initiative proof.",
      sourceConfidence: `Official Bain India page checked ${checked}`,
      availability: "watch",
      lastChecked: checked,
    },
  },
];
