export type FormChecklistSeed = {
  title: string;
  type: "application_form" | "leadership_form";
  url: string;
  status: string;
  notes: {
    target: string;
    region: string;
    stage: string;
    priority: "P1" | "P2" | "P3";
    cycle: string;
    deadline: string;
    action: string;
    why: string;
    documents: string[];
    route: string;
    evidence?: string;
    sourceConfidence: string;
  };
};

export const formChecklistSeeds: FormChecklistSeed[] = [
  {
    title: "LSE Graduate Application",
    type: "application_form",
    url: "https://www.lse.ac.uk/study-at-lse/graduate/prospective-students/how-to-apply",
    status: "admission_core",
    notes: {
      target: "LSE MSc Behavioural Science",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027 entry watch; 2026/27 cycle opened on 2025-10-08",
      deadline: "Apply early when next cycle opens",
      action: "Prepare the online application before the portal opens: programme choice, transcript, CV, statement, and two referees. LSE says the application is reviewed only after supporting documents are received.",
      why: "LSE warns competition is intense and early applications have a greater chance of meeting scholarship and visa deadlines.",
      documents: ["Transcript", "CV", "Statement of academic purpose", "Two references", "English test plan", "Research summary"],
      route: "applications",
      evidence: "Use the derealization/gaming paper and Mentally Prepare as the behavioural science proof spine.",
      sourceConfidence: "Official LSE graduate application guidance checked 2026-08-14",
    },
  },
  {
    title: "LSE Graduate Financial Support Application",
    type: "application_form",
    url: "https://www.lse.ac.uk/study-at-lse/graduate/fees-and-funding/pgt-application-overview",
    status: "scholarship_core",
    notes: {
      target: "LSE Graduate Support Scheme and LSE scholarships",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027 entry watch; 2026/27 deadline was 2026-04-23",
      deadline: "Submit only after LSE admission application opens the funding form",
      action: "Complete the Graduate Financial Support Application in the Graduate Applicant Portal after submitting the LSE application. You need an offer plus the funding form by the deadline.",
      why: "LSE uses the financial support application to consider Graduate Support Scheme and other eligible LSE scholarships, so this is not optional if funding matters.",
      documents: ["Funding statement", "Budget", "Family/financial evidence", "Admission application", "Offer condition watch", "Safe senders for lse.ac.uk"],
      route: "scholarships",
      evidence: "Tie financial need to a focused plan: behavioural science, mental health technology, and return-on-investment.",
      sourceConfidence: "Official LSE fees and funding page checked 2026-08-14",
    },
  },
  {
    title: "UCL Graduate Taught Application",
    type: "application_form",
    url: "https://www.ucl.ac.uk/study/prospective-students/graduate/how-apply/applying-graduate-taught-study-ucl",
    status: "admission_core",
    notes: {
      target: "UCL Behaviour Change MSc",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027 entry watch; check each course page for live deadline",
      deadline: "Apply well before scholarship deadlines",
      action: "Select the course page, check academic and English requirements, contact referees before starting, then submit the graduate taught application.",
      why: "UCL says scholarship funding is a separate application with different deadlines, and references must be complete for many funding forms.",
      documents: ["Transcript", "Personal statement", "CV", "References", "English requirement check", "Course-specific research fit paragraph"],
      route: "applications",
      evidence: "Use UX Researcher internship as practical behaviour-change/research experience.",
      sourceConfidence: "Official UCL graduate taught application guidance checked 2026-08-14",
    },
  },
  {
    title: "UCL Global Master's Scholarship",
    type: "application_form",
    url: "https://www.ucl.ac.uk/scholarships/ucl-global-masters-scholarship",
    status: "scholarship_core",
    notes: {
      target: "UCL Global Master's Scholarship",
      region: "UK",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027 entry watch; 2026/27 deadline was 2026-05-07",
      deadline: "Requires complete UCL admission application including references",
      action: "After submitting a complete UCL admission application, use Portico funding access to apply for eligible scholarships.",
      why: "UCL lists the Global Master's award as GBP 15,000 for overseas-fee prospective students from lower income backgrounds, with India ring-fenced places in 2026/27.",
      documents: ["UCL application number", "References submitted", "Fee status", "Financial need evidence", "Scholarship statement", "Budget"],
      route: "scholarships",
      evidence: "Frame need plus high-impact plan: behavioural science for student wellbeing and digital behaviour.",
      sourceConfidence: "Official UCL scholarship page checked 2026-08-14",
    },
  },
  {
    title: "Warwick Applicant Portal",
    type: "application_form",
    url: "https://warwick.ac.uk/study/postgraduate/courses/msc-behavioural-economics-science/",
    status: "admission_core",
    notes: {
      target: "Warwick MSc Behavioural and Economic Science",
      region: "UK",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027 entry watch; 2026 final deadline extended to 2026-08-02",
      deadline: "Prepare for early round when next cycle opens",
      action: "Use the Warwick course page and applicant portal checklist. Prepare quant/statistics evidence early because the course is methods-heavy.",
      why: "Warwick listed early, middle and final rounds for 2026, with the final date extended to 2 August 2026.",
      documents: ["Transcript", "CV", "Personal statement", "Reference", "Statistics/methods evidence", "IELTS Band B plan"],
      route: "applications",
      evidence: "Make a quantitative appendix for your research paper and UX internship methods.",
      sourceConfidence: "Official Warwick course page checked 2026-08-14",
    },
  },
  {
    title: "Erasmus Studielink + EUR Admissions Portal",
    type: "application_form",
    url: "https://www.eur.nl/en/ese/education/master/application/students-international-diploma/application-procedure-economics-and-business",
    status: "admission_core",
    notes: {
      target: "Erasmus MSc Economics and Business, Behavioural Economics specialisation",
      region: "Netherlands",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027 entry watch; 2026/27 opened on 2025-11-01",
      deadline: "Non-EU/EEA deadline was 2026-04-01",
      action: "Register for Master Economics and Business in Studielink, then complete the EUR Admissions Portal where you select Behavioural Economics and upload documents.",
      why: "EUR states Studielink alone is not the application; the EUR Admissions Portal is where the real application is completed.",
      documents: ["Diploma or graduation statement", "Official transcript", "Certified translations if needed", "EUR portal questions", "Application fee if applicable", "Specialisation choice"],
      route: "applications",
      evidence: "Show economics/statistics readiness plus consumer behaviour and UX research fit.",
      sourceConfidence: "Official Erasmus School of Economics application procedure checked 2026-08-14",
    },
  },
  {
    title: "Erasmus Trustfonds Scholarship",
    type: "application_form",
    url: "https://www.eur.nl/en/ese/education/master/fees-and-scholarships/scholarships-and-grants/erasmus-trustfonds-scholarship",
    status: "scholarship_core",
    notes: {
      target: "Erasmus Trustfonds Scholarship",
      region: "Netherlands",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027 entry watch; 2026/27 deadline was 2026-02-01",
      deadline: "Submit admission documents before scholarship deadline",
      action: "Apply for the eligible Erasmus scholarship after Studielink and EUR Admissions Portal submission. Build a detailed financial statement.",
      why: "For 2026/27, Erasmus Trustfonds required Studielink registration and submitted EUR portal documents before 1 February 2026.",
      documents: ["Studielink registration", "EUR application", "Financial statement", "Bachelor grades", "Immigration funding plan", "Scholarship application"],
      route: "scholarships",
      evidence: "Use academic excellence plus financial need and a high-ROI behavioural economics plan.",
      sourceConfidence: "Official Erasmus scholarship page checked 2026-08-14",
    },
  },
  {
    title: "Philip Hans Franses Scholarship",
    type: "application_form",
    url: "https://www.eur.nl/en/ese/education/master/fees-and-scholarships/scholarships-and-grants/philip-hans-franses-scholarship",
    status: "scholarship_core",
    notes: {
      target: "Erasmus School of Economics non-EEA scholarship",
      region: "Netherlands",
      stage: "Scholarship form",
      priority: "P1",
      cycle: "2027 entry watch; 2026/27 window was 2025-12-01 to 2026-02-01",
      deadline: "Build before 1 February cycle deadline",
      action: "Prepare motivation letter, financial statement, budget plan, certified transcript and GPA statement, then submit through Osiris Student when open.",
      why: "EUR lists four awards and a EUR 12,000 tuition-fee waiver for eligible non-EEA master students.",
      documents: ["Motivation letter", "Financial statement", "Budget plan", "Certified transcript", "GPA statement", "Osiris Student application"],
      route: "scholarships",
      evidence: "Make the motivation letter specific: Behavioural Economics plus mental-health/product impact in India.",
      sourceConfidence: "Official Erasmus scholarship page checked 2026-08-14",
    },
  },
  {
    title: "CMU MHCI Application",
    type: "application_form",
    url: "https://hcii.cmu.edu/academics/mhci/admissions",
    status: "admission_core",
    notes: {
      target: "Carnegie Mellon Master of Human-Computer Interaction",
      region: "USA",
      stage: "Admission portal",
      priority: "P1",
      cycle: "2027 entry watch; applications are typically due in January for fall admission",
      deadline: "Start portfolio and English score planning now",
      action: "Prepare MHCI application materials and optional examples of work. Confirm English test requirements because CMU does not waive them for non-native speakers.",
      why: "CMU MHCI allows optional work examples like portfolios, publications, reports and entrepreneurial projects, which is ideal for your UX internship and Mentally Prepare.",
      documents: ["Statement", "Resume", "Transcript", "Letters of recommendation", "IELTS 8.5 or TOEFL equivalent plan", "Portfolio/examples of work"],
      route: "applications",
      evidence: "Build one portfolio artifact from the UX Researcher internship plus one Mentally Prepare HCI case study.",
      sourceConfidence: "Official CMU MHCI admissions page checked 2026-08-14",
    },
  },
  {
    title: "IELTS Academic Registration",
    type: "application_form",
    url: "https://www.idp.com/india/ielts/book-a-test/",
    status: "test_core",
    notes: {
      target: "IELTS Academic for UK, Europe and USA applications",
      region: "Global",
      stage: "Test booking",
      priority: "P1",
      cycle: "Book once target score is realistic; India IELTS testing is through IDP",
      deadline: "Book early enough for score reporting and retake buffer",
      action: "Book IELTS Academic, not General Training. Keep a retake buffer because CMU MHCI has a very high IELTS minimum and LSE/UCL/Warwick need official English proof when required.",
      why: "English score is a gatekeeping form: it unlocks admission, visa and scholarships.",
      documents: ["Passport", "Test city/date", "Payment", "Target band plan", "Score recipient list", "Retake buffer"],
      route: "ielts",
      evidence: "Use IELTS as a readiness lever, not a last-minute paperwork item.",
      sourceConfidence: "IELTS/IDP India booking source checked 2026-08-14",
    },
  },
  {
    title: "UCAS Applying Hub",
    type: "application_form",
    url: "https://www.ucas.com/applying",
    status: "planning_reference",
    notes: {
      target: "UK application literacy reference",
      region: "UK",
      stage: "Planning reference",
      priority: "P3",
      cycle: "Reference only for your current master's targets unless a course page instructs UCAS",
      deadline: "Use before building your UK checklist",
      action: "Use UCAS to understand UK deadlines, personal statements, English tests and finance language. For LSE/UCL/Warwick graduate applications, follow the university's own portal.",
      why: "UCAS is useful for structure, but your current behavioural-science master's targets are direct university applications.",
      documents: ["UK timeline notes", "Personal statement guidance", "English test guidance", "Funding notes"],
      route: "sources",
      sourceConfidence: "Official UCAS applying hub checked 2026-08-14",
    },
  },
  {
    title: "BCG ASPIRE Women's Workshop",
    type: "leadership_form",
    url: "https://careers.bcg.com/global/en/featured-events/aspire-womens-workshop",
    status: "leadership_watch",
    notes: {
      target: "BCG ASPIRE Women's Workshop",
      region: "Global",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "2027 watch; 2026 workshop was 2026-05-20 to 2026-05-22",
      deadline: "Check country-specific links when applications reopen",
      action: "Apply through one participating office only. Prepare resume and country-specific documents, then complete the games assessment if invited.",
      why: "ASPIRE is a strong leadership and consulting signal; BCG states there is no participation fee and travel/accommodation are covered for the workshop.",
      documents: ["Leadership CV", "Transcript", "Office choice", "Geographic ties", "Games assessment readiness"],
      route: "opportunities",
      evidence: "Use Mentally Prepare, HPAIR, HP Dreams Unlocked, IIT Kharagpur and UX internship as leadership evidence.",
      sourceConfidence: "Official BCG ASPIRE page checked 2026-08-14",
    },
  },
  {
    title: "McKinsey Next Generation Women Leaders",
    type: "leadership_form",
    url: "https://www.mckinsey.com/next-generation-women-leaders",
    status: "leadership_watch",
    notes: {
      target: "McKinsey NGWL",
      region: "Global",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "2027 watch; Europe 2026 deadline was 2026-02-23",
      deadline: "Check Asia-Pacific and Europe pages when next cohort opens",
      action: "Prepare English resume, transcripts and office/function preference. Only apply where you have the required geographic or language fit.",
      why: "McKinsey NGWL asks for grades, work experience, extracurriculars, achievements, transcripts and office/function choices.",
      documents: ["Resume in English", "High school transcript", "University transcript", "Office/function choices", "Leadership examples"],
      route: "opportunities",
      evidence: "Frame yourself as psychology researcher plus mental-health product builder, not just a psychology student.",
      sourceConfidence: "Official McKinsey NGWL page checked 2026-08-14",
    },
  },
  {
    title: "EY NextGen Women India",
    type: "leadership_form",
    url: "https://www.ey.com/en_in/careers/nextgen-women",
    status: "leadership_watch",
    notes: {
      target: "EY NextGen Women in Strategy and Transactions",
      region: "India",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "Next India cycle watch; 2026 winner announced",
      deadline: "Use country-level EY page/contact when applications reopen",
      action: "Prepare a strategy/transactions aligned application around curiosity, problem solving, leadership and business impact.",
      why: "EY says the competition is for women currently studying at university level who are interested in Strategy and Transactions.",
      documents: ["Leadership CV", "Academic record", "Strategy interest paragraph", "Achievement examples", "Mentally Prepare impact"],
      route: "opportunities",
      evidence: "Connect consumer psychology, UX research and venture-building to strategy and transactions problem solving.",
      sourceConfidence: "Official EY India page checked 2026-08-14",
    },
  },
  {
    title: "Bain True North Scholarship for Women India",
    type: "leadership_form",
    url: "https://www.bain.com/careers/work-with-us/internships-programs/true-north-scholarship-for-women-india/",
    status: "leadership_watch",
    notes: {
      target: "Bain True North Scholarship for Women India",
      region: "India",
      stage: "Leadership programme",
      priority: "P2",
      cycle: "Apply in Spring 2027; 2026 applications closed",
      deadline: "Spring 2027 watch",
      action: "Prepare consulting CV, academic proof and leadership stories. Confirm eligibility because Bain India says the programme is for women in penultimate undergraduate year.",
      why: "The India programme offers a workshop, INR 75,000 scholarship opportunity and possible full-time interview route.",
      documents: ["Consulting CV", "Transcript", "Leadership story", "Problem-solving examples", "Penultimate-year eligibility check"],
      route: "opportunities",
      evidence: "Use HP Dreams Unlocked, HPAIR, IIT Kharagpur, Mentally Prepare and UX research as initiative proof.",
      sourceConfidence: "Official Bain India page checked 2026-08-14",
    },
  },
];
