import { sqlite } from "./client.js";

const statements = [
  `CREATE TABLE IF NOT EXISTS profile (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    degree TEXT NOT NULL,
    university TEXT NOT NULL,
    year TEXT NOT NULL,
    gpa REAL,
    ielts TEXT NOT NULL,
    research TEXT NOT NULL,
    startup TEXT NOT NULL,
    achievements TEXT NOT NULL,
    experience_tags TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS universities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    country TEXT NOT NULL,
    city TEXT NOT NULL,
    qs_ranking INTEGER,
    program_name TEXT NOT NULL,
    department TEXT NOT NULL,
    behavioral_science_fit INTEGER NOT NULL,
    consumer_psych_fit INTEGER NOT NULL,
    pm_fit INTEGER NOT NULL,
    research_fit INTEGER NOT NULL,
    startup_fit INTEGER NOT NULL,
    ielts_min REAL NOT NULL,
    gre_required INTEGER NOT NULL,
    gre_min INTEGER,
    tuition_usd INTEGER NOT NULL,
    living_cost_usd INTEGER NOT NULL,
    scholarship_available INTEGER NOT NULL,
    acceptance_rate REAL,
    acceptance_difficulty TEXT NOT NULL,
    stem_designation INTEGER NOT NULL,
    work_visa_years REAL NOT NULL,
    career_outcome_score INTEGER NOT NULL,
    roi_score INTEGER NOT NULL,
    tier TEXT NOT NULL,
    application_url TEXT NOT NULL,
    notes TEXT NOT NULL,
    is_estimated INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS university_shortlist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    university_id INTEGER NOT NULL,
    status TEXT NOT NULL,
    priority INTEGER NOT NULL,
    notes TEXT NOT NULL,
    deadline TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS scholarships (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    country TEXT NOT NULL,
    type TEXT NOT NULL,
    amount_usd INTEGER,
    deadline TEXT,
    eligibility_summary TEXT NOT NULL,
    url TEXT NOT NULL,
    winning_probability TEXT NOT NULL,
    status TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS careers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL UNIQUE,
    avg_salary_usd INTEGER NOT NULL,
    growth_rate REAL NOT NULL,
    demand_level TEXT NOT NULL,
    top_countries TEXT NOT NULL,
    required_skills TEXT NOT NULL,
    best_universities TEXT NOT NULL,
    roadmap_steps TEXT NOT NULL,
    description TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS research_papers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    target_journal TEXT,
    impact_factor REAL,
    submission_date TEXT,
    reviewer_comments TEXT,
    citation_count INTEGER NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ielts_progress (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    listening REAL,
    reading REAL,
    writing REAL,
    speaking REAL,
    overall REAL,
    is_mock INTEGER NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sop_documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    target_university_id INTEGER,
    content TEXT NOT NULL,
    version INTEGER NOT NULL,
    status TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS lor_contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    relationship TEXT NOT NULL,
    email TEXT,
    institution TEXT NOT NULL,
    strength_score INTEGER NOT NULL,
    status TEXT NOT NULL,
    deadline TEXT,
    target_universities TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    university_id INTEGER NOT NULL,
    program TEXT NOT NULL,
    status TEXT NOT NULL,
    deadline TEXT,
    submitted_date TEXT,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS visa_tracker (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    country TEXT NOT NULL UNIQUE,
    visa_type TEXT NOT NULL,
    status TEXT NOT NULL,
    funds_required_usd INTEGER NOT NULL,
    documents_checklist TEXT NOT NULL,
    work_rights_summary TEXT NOT NULL,
    stay_back_years REAL NOT NULL,
    timeline_notes TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS product_portfolio (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    metrics TEXT NOT NULL,
    status TEXT NOT NULL,
    url TEXT,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ai_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    report_type TEXT NOT NULL,
    content TEXT NOT NULL,
    generated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    priority TEXT NOT NULL,
    status TEXT NOT NULL,
    due_date TEXT,
    source TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    university_id INTEGER,
    role TEXT NOT NULL,
    email TEXT,
    linkedin TEXT,
    research_area TEXT,
    lab TEXT,
    recent_publications TEXT NOT NULL,
    match_score INTEGER NOT NULL,
    status TEXT NOT NULL,
    last_interaction TEXT,
    next_follow_up TEXT,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    url TEXT,
    status TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS course_intelligence (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    university_id INTEGER NOT NULL,
    program_name TEXT NOT NULL,
    intake_term TEXT NOT NULL,
    intake_frequency TEXT NOT NULL,
    intake_count INTEGER,
    intake_count_status TEXT NOT NULL,
    application_status TEXT NOT NULL,
    application_open_date TEXT,
    application_close_date TEXT,
    priority_funding_date TEXT,
    course_summary TEXT NOT NULL,
    module_highlights TEXT NOT NULL,
    research_highlights TEXT NOT NULL,
    research_fit_actions TEXT NOT NULL,
    requirement_highlights TEXT NOT NULL,
    source_urls TEXT NOT NULL,
    source_confidence TEXT NOT NULL,
    last_verified_at TEXT NOT NULL,
    next_check_date TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
];

export function initDb() {
  const transaction = sqlite.transaction(() => {
    for (const statement of statements) {
      sqlite.prepare(statement).run();
    }
  });
  transaction();
}
